export const portfolioData = {
  profile: {
    name: "Asim Ilyas Rathore",
    shortName: "Asim Ilyas Rathore",
    brandName: "Mr. Rathore",
    headline: "Software Engineering student focused on web development, machine learning, and scalable applications.",
    summary:
      "I create modern, scalable, and intelligent digital products by blending frontend design, APIs, and machine learning.",
    about:
      "I'm a passionate Software Engineering student at COMSATS University with expertise in full-stack development, machine learning, and building scalable applications.",
    location: "Abbottabad, Pakistan",
    avatar: "/imagesAchivemnts/profilePicNew1.png",
    logoAvatar: "/imagesAchivemnts/profilePicNew1.png",
    roles: [
      "Software Engineer",
      "Web Developer",
      "Machine Learning Engineer",
      "Game Developer",
      "DSA Specialist",
      "Deep Learning Engineer",
      "Problem Solver",
      "AI & ML Engineer",
      "Clean Code Developer",
      "Creative Thinker",
    ],
  },
  skills: [
    {
      icon: "monitor",
      color: "text-blue-500",
      title: "Web Development",
      description: "Building responsive and modern websites using React, TypeScript, and integrating backend APIs efficiently.",
    },
    {
      icon: "gamepad",
      color: "text-amber-500",
      title: "Game Development",
      description: "Creating immersive 2D/3D games using Unity & C#, with interactive mechanics and smooth gameplay.",
    },
    {
      icon: "brain",
      color: "text-purple-500",
      title: "Machine Learning",
      description: "Implementing intelligent systems and predictive models using Python, TensorFlow, and scikit-learn.",
    },
    {
      icon: "database",
      color: "text-emerald-500",
      title: "Database Expertise",
      description: "Hands-on experience in SQL & MS SQL Server for secure, scalable, and efficient data management.",
    },
    {
      icon: "code",
      color: "text-orange-500",
      title: "Data Structures & Algorithms",
      description: "Strong understanding of core DSA concepts for optimized, clean, and efficient solutions.",
    },
    {
      icon: "rocket",
      color: "text-rose-500",
      title: "Problem Solving",
      description: "Passionate about tackling challenges with logical thinking and optimized solutions.",
    },
  ],
  projectCategories: [
    "All",
    "Web Development",
    "Machine Learning",
    "Game Development",
    "Data Structures",
    "Desktop Application",
  ],
  projects: [
    {
      id: 1,
      title: "Bangalore House Prediction (Regression Model)",
      description:
        "Built a regression model using Python and Flask to predict house prices in Bangalore. Includes feature engineering, data preprocessing with Pandas, and a web-based interface.",
      techStack: ["Python", "Flask", "Pandas", "JavaScript", "HTML", "CSS"],
      url: "https://github.com/asimalyas/Python-Projects/tree/main/BanglorHousePrizePredictionRegressionModelProject",
      categories: ["Machine Learning", "Web Development"],
    },
    {
      id: 2,
      title: "Celebrity Recognition (Classification Model)",
      description:
        "SVM-based ML model with OpenCV for real-time face recognition. Deployed with Flask, classifies celebrities using wavelet transformations.",
      techStack: ["Python", "OpenCV", "Wavelet", "Flask", "HTML", "CSS"],
      url: "https://github.com/asimalyas/Python-Projects/tree/main/CelebrityFaceRecongization",
      categories: ["Machine Learning", "Web Development"],
    },
    {
      id: 3,
      title: "Archery Quest Game",
      description:
        "A Unity-based archery quest game with two levels of increasing difficulty. Implements physics-based arrow shooting, scoring, and immersive gameplay.",
      techStack: ["Unity", "C#"],
      url: "https://github.com/asimalyas/Game-In-Unity-",
      categories: ["Game Development"],
    },
    {
      id: 4,
      title: "Runner Game",
      description: "An endless runner game built with Unity and C#. Features dynamic obstacles, collision detection, and increasing difficulty.",
      techStack: ["Unity", "C#"],
      url: "https://github.com/asimalyas/Game-In-Unity-",
      categories: ["Game Development"],
    },
    {
      id: 21,
      title: "Personal Developer Portfolio with AI Integration",
      description:
        "Built a responsive developer portfolio to showcase projects, skills, achievements, and experience, with an integrated AI-powered assistant for interactive recruiter Q&A.",
      techStack: ["React", "TypeScript", "Vite", "CSS", "AI Integration", "Vercel"],
      url: "https://github.com/asimalyas/Portfolio",
      categories: ["Web Development", "Machine Learning"],
    },
    {
      id: 19,
      title: "MediConnect - Smart Healthcare Platform",
      description: "Enables patients to book medical assistants for home checkups. Doctors review data remotely with role-based dashboards.",
      techStack: ["TypeScript", "React", "Tailwind CSS", "Supabase", "RBAC"],
      url: "https://github.com/asimalyas/MediConnect",
      categories: ["Web Development"],
    },
    {
      id: 20,
      title: "Entry Test Quiz",
      description:
        "AI-powered entry test practice platform where students can paste MCQs, auto-format questions, extract MCQs from PDFs/images, generate questions from lecture slides, practice with timer modes, skip/retry questions, review results, and ask an AI tutor for help.",
      techStack: ["React", "TypeScript", "Vite", "CSS", "Gemini AI", "PDF.js", "Vercel", "LocalStorage"],
      url: "https://quiz-test-app-five.vercel.app/",
      categories: ["Web Development", "Machine Learning"],
    },
    {
      id: 5,
      title: "Attendance Management System",
      description: "Web-based system for tracking student attendance. Includes admin and student panels, authentication, and attendance reports.",
      techStack: ["JavaScript", "HTML", "CSS"],
      url: "https://github.com/asimalyas/WebTasks/tree/main/attendance-management-system",
      categories: ["Web Development"],
    },
        {
      id: 8,
      title: "CodeCrux",
      description: "A React-based platform for practicing and managing programming questions with user-friendly UI for browsing and solving problems.",
      techStack: ["React", "JavaScript"],
      url: "https://github.com/asimalyas/React_projects/tree/main/codecrux",
      categories: ["Web Development"],
    },
    {
      id: 9,
      title: "Huffman Coding",
      description: "Java implementation of Huffman Coding for text compression. Demonstrates encoding and decoding algorithms for file compression.",
      techStack: ["Java"],
      url: "https://github.com/asimalyas/DataStructure",
      categories: ["Data Structures"],
    },
    {
      id: 10,
      title: "Stop Watch",
      description: "React-based stopwatch with Start, Stop, and Reset functionality. Demonstrates React hooks for state and real-time updates.",
      techStack: ["React", "JavaScript"],
      url: null,
      categories: ["Web Development"],
    },
    {
      id: 11,
      title: "Library Management System",
      description: "Desktop application built with Java and OOP principles. Supports adding books, tracking issued books, and managing student records.",
      techStack: ["Java", "OOP"],
      url: "https://github.com/asimalyas/OOP",
      categories: ["Desktop Application"],
    },
    {
      id: 12,
      title: "E-Learning Course Platform",
      description: "Java-based desktop platform for online learning with authentication, course progress tracking, and MS SQL Server backend.",
      techStack: ["Java", "MS SQL Server", "JDBC"],
      url: null,
      categories: ["Desktop Application"],
    },
    {
      id: 6,
      title: "Amazon Home Page Clone",
      description: "Responsive front-end clone of Amazon's homepage with navbar, product showcases, and grid layouts using pure HTML/CSS.",
      techStack: ["HTML", "CSS"],
      url: "https://github.com/asimalyas/WebTasks/tree/main/Amazon%20clone",
      categories: ["Web Development"],
    },
    {
      id: 7,
      title: "Netflix Home Page Clone",
      description: "Frontend clone of Netflix's homepage with responsive layouts, hero banner, movie thumbnails, and hover effects.",
      techStack: ["HTML", "CSS"],
      url: "https://github.com/asimalyas/WebTasks/tree/main/Netflix%20frontend",
      categories: ["Web Development"],
    },

    {
      id: 13,
      title: "Note Keeper",
      description: "React application for managing personal notes. Users can add, delete, and organize notes with a responsive interface.",
      techStack: ["React", "JavaScript"],
      url: "https://github.com/asimalyas/React_projects/tree/main/noter-keeper",
      categories: ["Web Development"],
    },
    {
      id: 14,
      title: "Currency Converter",
      description: "Real-time currency converter with API integration. Fetches live exchange rates with a clean, responsive UI.",
      techStack: ["JavaScript", "HTML", "CSS"],
      url: "https://github.com/asimalyas/WebTasks/tree/main/currencyChanger",
      categories: ["Web Development"],
    },
    {
      id: 15,
      title: "QR Image Generator",
      description: "Full-stack project using React and Node.js to generate QR codes dynamically. Users can input text/links and download QR codes.",
      techStack: ["Node.js", "React"],
      url: "https://github.com/asimalyas/React_projects/tree/main/QR%2BCode%2BProject",
      categories: ["Web Development"],
    },
    {
      id: 16,
      title: "Rock, Paper, Scissors, Fire Game",
      description: "Extended Rock-Paper-Scissors with an additional 'Fire' element. Features interactive gameplay and custom rules.",
      techStack: ["JavaScript", "HTML", "CSS"],
      url: "https://github.com/asimalyas/WebTasks/tree/main/RockSesiorFire",
      categories: ["Web Development"],
    },
    {
      id: 17,
      title: "Hepta",
      description: "Modern frontend travel website with elegant layouts, responsive design, and sections for destinations and services.",
      techStack: ["React", "HTML", "CSS", "JavaScript"],
      url: "https://github.com/asimalyas/React_projects/tree/main/hepta",
      categories: ["Web Development"],
    },
    {
      id: 18,
      title: "Heart Disease Prediction (Classification)",
      description: "Random Forest classification model for predicting heart disease using tabular data with data cleaning and feature engineering.",
      techStack: ["Python", "Flask", "HTML", "CSS", "JavaScript", "RandomForest"],
      url: "https://github.com/asimalyas/Python-Projects/tree/main",
      categories: ["Machine Learning", "Web Development"],
    },
   

  ],
  education: [
    {
      id: 1,
      years: "2022 - Present",
      degree: "BS Software Engineering (8th Semester)",
      institution: "COMSATS University Islamabad, Abbottabad Campus",
      grade: "CGPA: 3.90/4.00",
      image: "/imagesAchivemnts/comsats.png",
    },
    {
      id: 2,
      years: "2018 - 2020",
      degree: "FSc (Pre-Medical)",
      institution: "Gov't Model Science College, Muzaffarabad, AJK",
      grade: "Percentage: 91%",
      image: "/imagesAchivemnts/muzaffarabad.png",
    },
    {
      id: 3,
      years: "2016 - 2018",
      degree: "Matric (Science)",
      institution: "Haveli Model Science College, Kahuta, AJK",
      grade: "Percentage: 90%",
      image: "/imagesAchivemnts/kahuta.png",
    },
  ],
  achievementCategories: ["All", "Studies", "Projects", "Activities", "Sports", "Skills"],
  achievements: [
    {
      id: 1,
      title: "Certificate of Excellence in Database",
      description: "Won the Inter-Subject Project Competition in Database at COMSATS University, January 2025.",
      image: "/imagesAchivemnts/DatabaseUniWinnerProject.jpg",
      category: ["Studies", "Projects"],
    },
    {
      id: 2,
      title: "Campus Honor Roll - 5th Semester",
      description: "Perfect SGPA of 4.0/4.0 in Fall 2024 at COMSATS University Islamabad.",
      image: "/imagesAchivemnts/5thSemResult.jpg",
      category: ["Studies"],
    },
    {
      id: 3,
      title: "Communication Event Certificate",
      description: "Awarded for organizing the Communication Event, December 2022.",
      image: "/imagesAchivemnts/CumunicationEventCertificate.jpg",
      category: ["Activities"],
    },
    {
      id: 4,
      title: "Campus Honor Roll - 3rd Semester",
      description: "Perfect SGPA of 4.0/4.0 in Fall 2023 Session.",
      image: "/imagesAchivemnts/3rdSem.png",
      category: ["Studies"],
    },
    {
      id: 5,
      title: "Excellence in Computer Network",
      description: "Runner up in Inter-Subject Project Competition, January 2025.",
      image: "/imagesAchivemnts/CNProject.jpg",
      category: ["Studies", "Projects"],
    },
    {
      id: 6,
      title: "CCNA: Introduction to Networks",
      description: "Completed through Cisco Networking Academy, September 2025.",
      image: "/imagesAchivemnts/networking.jpg",
      category: ["Studies", "Skills"],
    },
    {
      id: 7,
      title: "Convocation 2023 Appreciation",
      description: "Ushers team in the 22nd & 23rd Convocation.",
      image: "/imagesAchivemnts/convocation.jpg",
      category: ["Activities"],
    },
    {
      id: 8,
      title: "Deep Learning Workshop",
      description: "4-day workshop by Dept. of Electrical Engineering, November 2025.",
      image: "/imagesAchivemnts/DL workshop.jpg",
      category: ["Studies", "Skills", "Activities"],
    },
    {
      id: 9,
      title: "Deep Learning & NLP Workshop",
      description: "Robotics Club workshop on DL and NLP at COMSATS.",
      image: "/imagesAchivemnts/nlp workshop rebotics clu.png",
      category: ["Studies", "Skills", "Activities"],
    },
    {
      id: 10,
      title: "Campus Honor Roll - 6th Semester",
      description: "Perfect CGPA 4.0/4.0 in BS Software Engineering Semester 6.",
      image: "/imagesAchivemnts/semester 6th awarded.png",
      category: ["Studies"],
    },
  ],
  experience: {
    summary:
      "This section is reserved for verified internships, jobs, freelance work, and professional roles.",
    availability: "Open to internships, junior software engineering roles, React/frontend roles, and AI/ML-focused project opportunities.",
    placeholderTitle: "Professional experience coming soon",
    placeholderDescription:
      "Internships, jobs, and verified professional experience will be added here as they are completed.",
    roles: [],
    focusAreas: [
      "Frontend engineering with React, TypeScript, Vite, and Tailwind CSS",
      "Machine learning model development and Flask-based deployment",
      "AI-assisted product features, prompt design, and secure API integration",
      "Database-backed applications using SQL and MS SQL Server",
    ],
    futureEntryFields: [
      "Role title and company name",
      "Internship or job type, period, and location",
      "Company logo or image if available",
      "Responsibilities, technologies, certificate link, and company website",
    ],
    note: "No formal internship, job, or professional role is listed in the current portfolio data.",
  },
  links: {
    github: "https://github.com/asimalyas",
    linkedin: "https://www.linkedin.com/in/muhammad-asim-ilyas-a38b263a2",
    resume:
      "https://1drv.ms/b/c/cacb8574e4143f96/IQDndPwfiBC3T7-h0IuWVWbyAe2Bro3mHw9OHb2SaDe3rz4?e=u6Hdfp",
  },
  contact: {
    email: "asimalyas44440@gmail.com",
    phones: ["+92 355 6074440", "+92 320 1587154"],
    location: "Abbottabad, Pakistan",
  },
  suggestedQuestions: [
    "Why should recruiters shortlist Asim?",
    "Which projects best prove Asim's React experience?",
    "Summarize Asim for a junior software engineer role.",
    "What AI and machine learning projects has Asim built?",
    "How can I contact Asim?",
  ],
};
