-- Optional seed data generated from shared/portfolio.js.
-- Run supabase/schema.sql first, then this file if you want the admin dashboard to start with the current portfolio content.

truncate table public.skills, public.projects, public.education, public.experiences, public.certificates, public.achievements restart identity;

insert into public.skills (title, description, icon, color, sort_order, active) values ('Web Development', 'Building responsive and modern websites using React, TypeScript, and integrating backend APIs efficiently.', 'monitor', 'text-blue-500', 1, true);
insert into public.skills (title, description, icon, color, sort_order, active) values ('Game Development', 'Creating immersive 2D/3D games using Unity & C#, with interactive mechanics and smooth gameplay.', 'gamepad', 'text-amber-500', 2, true);
insert into public.skills (title, description, icon, color, sort_order, active) values ('Machine Learning', 'Implementing intelligent systems and predictive models using Python, TensorFlow, and scikit-learn.', 'brain', 'text-purple-500', 3, true);
insert into public.skills (title, description, icon, color, sort_order, active) values ('Database Expertise', 'Hands-on experience in SQL & MS SQL Server for secure, scalable, and efficient data management.', 'database', 'text-emerald-500', 4, true);
insert into public.skills (title, description, icon, color, sort_order, active) values ('Data Structures & Algorithms', 'Strong understanding of core DSA concepts for optimized, clean, and efficient solutions.', 'code', 'text-orange-500', 5, true);
insert into public.skills (title, description, icon, color, sort_order, active) values ('Problem Solving', 'Passionate about tackling challenges with logical thinking and optimized solutions.', 'rocket', 'text-rose-500', 6, true);

insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Bangalore House Prediction (Regression Model)', 'Built a regression model using Python and Flask to predict house prices in Bangalore. Includes feature engineering, data preprocessing with Pandas, and a web-based interface.', array['Python', 'Flask', 'Pandas', 'JavaScript', 'HTML', 'CSS'], array['Machine Learning', 'Web Development'], 'https://github.com/asimalyas/Python-Projects/tree/main/BanglorHousePrizePredictionRegressionModelProject', 1, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Celebrity Recognition (Classification Model)', 'SVM-based ML model with OpenCV for real-time face recognition. Deployed with Flask, classifies celebrities using wavelet transformations.', array['Python', 'OpenCV', 'Wavelet', 'Flask', 'HTML', 'CSS'], array['Machine Learning', 'Web Development'], 'https://github.com/asimalyas/Python-Projects/tree/main/CelebrityFaceRecongization', 2, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Archery Quest Game', 'A Unity-based archery quest game with two levels of increasing difficulty. Implements physics-based arrow shooting, scoring, and immersive gameplay.', array['Unity', 'C#'], array['Game Development'], 'https://github.com/asimalyas/Game-In-Unity-', 3, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Runner Game', 'An endless runner game built with Unity and C#. Features dynamic obstacles, collision detection, and increasing difficulty.', array['Unity', 'C#'], array['Game Development'], 'https://github.com/asimalyas/Game-In-Unity-', 4, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Personal Developer Portfolio with AI Integration', 'Built a responsive developer portfolio to showcase projects, skills, achievements, and experience, with an integrated AI-powered assistant for interactive recruiter Q&A.', array['React', 'TypeScript', 'Vite', 'CSS', 'AI Integration', 'Vercel'], array['Web Development', 'Machine Learning'], 'https://github.com/asimalyas/Portfolio', 5, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('MediConnect - Smart Healthcare Platform', 'Enables patients to book medical assistants for home checkups. Doctors review data remotely with role-based dashboards.', array['TypeScript', 'React', 'Tailwind CSS', 'Supabase', 'RBAC'], array['Web Development'], 'https://github.com/asimalyas/MediConnect', 6, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Entry Test Quiz', 'AI-powered entry test practice platform where students can paste MCQs, auto-format questions, extract MCQs from PDFs/images, generate questions from lecture slides, practice with timer modes, skip/retry questions, review results, and ask an AI tutor for help.', array['React', 'TypeScript', 'Vite', 'CSS', 'Gemini AI', 'PDF.js', 'Vercel', 'LocalStorage'], array['Web Development', 'Machine Learning'], 'https://quiz-test-app-five.vercel.app/', 7, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Attendance Management System', 'Web-based system for tracking student attendance. Includes admin and student panels, authentication, and attendance reports.', array['JavaScript', 'HTML', 'CSS'], array['Web Development'], 'https://github.com/asimalyas/WebTasks/tree/main/attendance-management-system', 8, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('CodeCrux', 'A React-based platform for practicing and managing programming questions with user-friendly UI for browsing and solving problems.', array['React', 'JavaScript'], array['Web Development'], 'https://github.com/asimalyas/React_projects/tree/main/codecrux', 9, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Huffman Coding', 'Java implementation of Huffman Coding for text compression. Demonstrates encoding and decoding algorithms for file compression.', array['Java'], array['Data Structures'], 'https://github.com/asimalyas/DataStructure', 10, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Stop Watch', 'React-based stopwatch with Start, Stop, and Reset functionality. Demonstrates React hooks for state and real-time updates.', array['React', 'JavaScript'], array['Web Development'], null, 11, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Library Management System', 'Desktop application built with Java and OOP principles. Supports adding books, tracking issued books, and managing student records.', array['Java', 'OOP'], array['Desktop Application'], 'https://github.com/asimalyas/OOP', 12, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('E-Learning Course Platform', 'Java-based desktop platform for online learning with authentication, course progress tracking, and MS SQL Server backend.', array['Java', 'MS SQL Server', 'JDBC'], array['Desktop Application'], null, 13, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Amazon Home Page Clone', 'Responsive front-end clone of Amazon''s homepage with navbar, product showcases, and grid layouts using pure HTML/CSS.', array['HTML', 'CSS'], array['Web Development'], 'https://github.com/asimalyas/WebTasks/tree/main/Amazon%20clone', 14, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Netflix Home Page Clone', 'Frontend clone of Netflix''s homepage with responsive layouts, hero banner, movie thumbnails, and hover effects.', array['HTML', 'CSS'], array['Web Development'], 'https://github.com/asimalyas/WebTasks/tree/main/Netflix%20frontend', 15, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Note Keeper', 'React application for managing personal notes. Users can add, delete, and organize notes with a responsive interface.', array['React', 'JavaScript'], array['Web Development'], 'https://github.com/asimalyas/React_projects/tree/main/noter-keeper', 16, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Currency Converter', 'Real-time currency converter with API integration. Fetches live exchange rates with a clean, responsive UI.', array['JavaScript', 'HTML', 'CSS'], array['Web Development'], 'https://github.com/asimalyas/WebTasks/tree/main/currencyChanger', 17, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('QR Image Generator', 'Full-stack project using React and Node.js to generate QR codes dynamically. Users can input text/links and download QR codes.', array['Node.js', 'React'], array['Web Development'], 'https://github.com/asimalyas/React_projects/tree/main/QR%2BCode%2BProject', 18, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Rock, Paper, Scissors, Fire Game', 'Extended Rock-Paper-Scissors with an additional ''Fire'' element. Features interactive gameplay and custom rules.', array['JavaScript', 'HTML', 'CSS'], array['Web Development'], 'https://github.com/asimalyas/WebTasks/tree/main/RockSesiorFire', 19, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Hepta', 'Modern frontend travel website with elegant layouts, responsive design, and sections for destinations and services.', array['React', 'HTML', 'CSS', 'JavaScript'], array['Web Development'], 'https://github.com/asimalyas/React_projects/tree/main/hepta', 20, true);
insert into public.projects (title, description, tech_stack, categories, url, sort_order, active) values ('Heart Disease Prediction (Classification)', 'Random Forest classification model for predicting heart disease using tabular data with data cleaning and feature engineering.', array['Python', 'Flask', 'HTML', 'CSS', 'JavaScript', 'RandomForest'], array['Machine Learning', 'Web Development'], 'https://github.com/asimalyas/Python-Projects/tree/main', 21, true);

insert into public.education (years, degree, institution, grade, image_url, sort_order, active) values ('2022 - Present', 'BS Software Engineering (8th Semester)', 'COMSATS University Islamabad, Abbottabad Campus', 'CGPA: 3.90/4.00', '/imagesAchivemnts/comsats.png', 1, true);
insert into public.education (years, degree, institution, grade, image_url, sort_order, active) values ('2018 - 2020', 'FSc (Pre-Medical)', 'Gov''t Model Science College, Muzaffarabad, AJK', 'Percentage: 91%', '/imagesAchivemnts/muzaffarabad.png', 2, true);
insert into public.education (years, degree, institution, grade, image_url, sort_order, active) values ('2016 - 2018', 'Matric (Science)', 'Haveli Model Science College, Kahuta, AJK', 'Percentage: 90%', '/imagesAchivemnts/kahuta.png', 3, true);

insert into public.achievements (title, description, image_url, categories, sort_order, active) values ('Certificate of Excellence in Database', 'Won the Inter-Subject Project Competition in Database at COMSATS University, January 2025.', '/imagesAchivemnts/DatabaseUniWinnerProject.jpg', array['Studies', 'Projects'], 1, true);
insert into public.achievements (title, description, image_url, categories, sort_order, active) values ('Campus Honor Roll - 5th Semester', 'Perfect SGPA of 4.0/4.0 in Fall 2024 at COMSATS University Islamabad.', '/imagesAchivemnts/5thSemResult.jpg', array['Studies'], 2, true);
insert into public.achievements (title, description, image_url, categories, sort_order, active) values ('Campus Honor Roll - 3rd Semester', 'Perfect SGPA of 4.0/4.0 in Fall 2023 Session.', '/imagesAchivemnts/3rdSem.png', array['Studies'], 4, true);
insert into public.achievements (title, description, image_url, categories, sort_order, active) values ('Excellence in Computer Network', 'Runner up in Inter-Subject Project Competition, January 2025.', '/imagesAchivemnts/CNProject.jpg', array['Studies', 'Projects'], 5, true);
insert into public.achievements (title, description, image_url, categories, sort_order, active) values ('Campus Honor Roll - 6th Semester', 'Perfect CGPA 4.0/4.0 in BS Software Engineering Semester 6.', '/imagesAchivemnts/semester 6th awarded.png', array['Studies'], 10, true);



insert into public.certificates (title, issuer, date_label, description, image_url, credential_url, categories, sort_order, active) values ('Communication Event Certificate', 'COMSATS University', 'December 2022', 'Awarded for organizing the Communication Event, December 2022.', '/imagesAchivemnts/CumunicationEventCertificate.jpg', null, array['Activities'], 1, true);
insert into public.certificates (title, issuer, date_label, description, image_url, credential_url, categories, sort_order, active) values ('CCNA: Introduction to Networks', 'Cisco Networking Academy', 'September 2025', 'Completed through Cisco Networking Academy, September 2025.', '/imagesAchivemnts/networking.jpg', null, array['Studies', 'Skills'], 2, true);
insert into public.certificates (title, issuer, date_label, description, image_url, credential_url, categories, sort_order, active) values ('Convocation 2023 Appreciation', 'COMSATS University', '2023', 'Ushers team in the 22nd & 23rd Convocation.', '/imagesAchivemnts/convocation.jpg', null, array['Activities'], 3, true);
insert into public.certificates (title, issuer, date_label, description, image_url, credential_url, categories, sort_order, active) values ('Deep Learning Workshop', 'COMSATS University', 'November 2025', '4-day workshop by Dept. of Electrical Engineering, November 2025.', '/imagesAchivemnts/DL workshop.jpg', null, array['Studies', 'Skills', 'Activities'], 4, true);
insert into public.certificates (title, issuer, date_label, description, image_url, credential_url, categories, sort_order, active) values ('Deep Learning & NLP Workshop', 'COMSATS University', '', 'Robotics Club workshop on DL and NLP at COMSATS.', '/imagesAchivemnts/nlp workshop rebotics clu.png', null, array['Studies', 'Skills', 'Activities'], 5, true);
